/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as _notFoundRouteImport } from './routes/__not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImagesUploadRouteImport } from ./routes/images/uploadad'
import { Route as CreatorsApplyRouteImport } from './routes/creators/apply'

const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const _notFoundRoute = _notFoundRouteImport.update({
  id: '/__not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesUploadRoute = ImagesUploadRouteImport.update({
  id: '/images/upload',
  path: '/images/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsApplyRoute = CreatorsApplyRouteImport.update({
  id: '/creators/apply',
  path: '/creators/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/creators/apply': typeof CreatorsApplyRoute
  '/images/upload': typeof ImagesUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/creators/apply': typeof CreatorsApplyRoute
  '/images/upload': typeof ImagesUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__not-found': typeof _notFoundRoute
  '/catalog': typeof CatalogRoute
  '/creators/apply': typeof CreatorsApplyRoute
  '/images/upload': typeof ImagesUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalog' | '/creators/apply' | '/images/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/creators/apply' | '/images/upload'
  id:
    | '__root__'
    | '/'
    | '/__not-found'
    | '/catalog'
    | '/creators/apply'
    | '/images/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _notFoundRoute: typeof _notFoundRoute
  CatalogRoute: typeof CatalogRoute
  CreatorsApplyRoute: typeof CreatorsApplyRoute
  ImagesUploadRoute: typeof ImagesUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__not-found': {
      id: '/__not-found'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _notFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/upload': {
      id: '/images/upload'
      path: '/images/upload'
      fullPath: '/images/upload'
      preLoaderRoute: typeof ImagesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/apply': {
      id: '/creators/apply'
      path: '/creators/apply'
      fullPath: '/creators/apply'
      preLoaderRoute: typeof CreatorsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _notFoundRoute: _notFoundRoute,
  CatalogRoute: CatalogRoute,
  CreatorsApplyRoute: CreatorsApplyRoute,
  ImagesUploadRoute: ImagesUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
